# Generated by Django 3.0.10 on 2020-10-04 15:03

from django.db import migrations, models
import django.db.models.deletion
import htch.peliculas.models.turno


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el dato fue creado', null=True, verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha en la ue fue modificado por ultima vez', null=True, verbose_name='modificado el')),
                ('id_peli', models.AutoField(primary_key=True, serialize=False)),
                ('peli_nom', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Pelicula')),
                ('peli_img', models.URLField(unique=True, verbose_name='Image')),
                ('peli_publi', models.DateField()),
                ('peli_estado', models.BooleanField(default=False, verbose_name='Activo')),
            ],
            options={
                'verbose_name_plural': 'Peliculas',
                'db_table': 't_pelicula',
                'ordering': ['peli_nom'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el dato fue creado', null=True, verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha en la ue fue modificado por ultima vez', null=True, verbose_name='modificado el')),
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('turno_fech', models.DateField(validators=[htch.peliculas.models.turno.fecha_validator])),
                ('turno_hora', models.CharField(max_length=5)),
                ('turno_estado', models.BooleanField()),
                ('pelicula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peliculas.Pelicula')),
            ],
            options={
                'verbose_name_plural': 'Turnos',
                'db_table': 't_turno',
                'ordering': ['turno_hora'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
